spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods:
              - GET
      routes:
        - id: hello-service
          uri: http://localhost:8082
          predicates:
            - Path=/hello/**
        - id: name-service
          uri: http://localhost:8081
          predicates:
            - Path=/name/**
  application:
    name: api-gateway

server:
  port: 8083